# Generated by Django 4.2.1 on 2023-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_resevations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resevations',
            name='date',
            field=models.DateField(),
        ),
    ]
